### PR TITLE
Car view

### PR DESCRIPTION
**Pull request by neverfall**
screen shot 2016-01-13 at 7 06 16 pm
screen shot 2016-01-13 at 7 06 27 pm

### CODE REVIEW

**Comment by aleks279** [comment]
Pushing the `/bower_components` folder to git was a rather dumb move... one only needs the `package.json` and `bower install` to get those...

**Comment by neverfall** [comment]
i put the bower_components in the gitignore

**Comment by neverfall** [comment]
done i fix it

**Comment by neverfall** [comment]
TO DO:
the vm=this is not working in ionic 1.7.12, issue #2499 of ionic
for now using vm=$scope

**Pull request merged**
